import type { PhotoSpec } from "./types";

export const photoSpecs: PhotoSpec[] = [
  {
    id: "us-niv-digital",
    name: "非移民签证 · 数字照片",
    country: "美国",
    mode: "在线申请",
    widthPx: 600,
    heightPx: 600,
    maxBytes: 240 * 1024,
    headRatio: [0.5, 0.69],
    note: "白色或近白背景；头部占照片总高度 50%–69%。",
    verifiedAt: "2026-07-21",
    source: "https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/photos.html",
  },
  {
    id: "ca-trv-print",
    name: "临时居民签证 · 纸质照片",
    country: "加拿大",
    mode: "纸质递交",
    widthPx: 827,
    heightPx: 1063,
    widthMm: 35,
    heightMm: 45,
    headRatio: [31 / 45, 36 / 45],
    note: "至少 35 × 45 mm；下巴至头顶 31–36 mm。像素按 600 DPI 导出，仅供打印排版参考。",
    verifiedAt: "2026-07-21",
    source: "https://www.canada.ca/en/immigration-refugees-citizenship/services/application/application-forms-guides/temporary-resident-visa-application-photograph-specifications.html",
  },
  {
    id: "gb-visa-digital",
    name: "签证申请 · 数字照片",
    country: "英国",
    mode: "在线申请",
    widthPx: 600,
    heightPx: 750,
    minBytes: 50 * 1024,
    maxBytes: 6 * 1024 * 1024,
    note: "至少 600 × 750 px，JPEG，50 KB–6 MB，竖向照片。",
    verifiedAt: "2026-07-21",
    source: "https://www.gov.uk/guidance/how-to-take-a-photo-for-a-visa-application-or-permission",
  },
  {
    id: "schengen-short-stay-print",
    name: "短期签证 · 纸质照片",
    country: "申根",
    mode: "纸质递交",
    widthPx: 827,
    heightPx: 1063,
    widthMm: 35,
    heightMm: 45,
    headRatio: [0.7, 0.8],
    note: "35 × 45 mm；近期彩色正面照，浅色背景，脸部约占照片高度 70%–80%。递交前请核对受理国要求。",
    verifiedAt: "2026-07-21",
    source: "https://home-affairs.ec.europa.eu/document/download/71052552-a6e7-4581-9857-04fb5ace6bc5_en",
  },
  {
    id: "jp-entry-visa-print",
    name: "入境签证 · 纸质照片",
    country: "日本",
    mode: "申请表粘贴",
    widthPx: 827,
    heightPx: 1063,
    widthMm: 35,
    heightMm: 45,
    note: "约 45 × 35 mm；正面、脱帽、无背景，通常要求近 6 个月拍摄。请核对所属领区使用的申请表版本。",
    verifiedAt: "2026-07-21",
    source: "https://www.mofa.go.jp/j_info/visit/visa/pdfs/application1_k.pdf",
  },
  {
    id: "kr-entry-visa-print",
    name: "入境签证 · 纸质照片",
    country: "韩国",
    mode: "申请表粘贴",
    widthPx: 827,
    heightPx: 1063,
    widthMm: 35,
    heightMm: 45,
    note: "35 × 45 mm；近 6 个月拍摄、正面免冠、白色或近白背景的彩色照片。",
    verifiedAt: "2026-07-21",
    source: "https://overseas.mofa.go.kr/upload/cntnts/cn-guangzhou-zh/visa_gw.pdf",
  },
];

export const pendingSpecs = [
  { country: "澳大利亚", detail: "ImmiAccount 内上传 JPG 并框选；官方未给出统一强制像素" },
  { country: "新西兰", detail: "下一批：核验在线申请尺寸与文件限制" },
];
