import type { PhotoSpec } from "./types";

export const photoSpecs: PhotoSpec[] = [
  {
    id: "us-niv-digital",
    name: "非移民签证 · 数字照片",
    country: "美国",
    mode: "在线申请",
    widthPx: 600,
    heightPx: 600,
    maxBytes: 240 * 1024,
    headRatio: [0.5, 0.69],
    note: "白色或近白背景；头部占照片总高度 50%–69%。",
    verifiedAt: "2026-07-21",
    source: "https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/photos.html",
  },
  {
    id: "ca-trv-print",
    name: "临时居民签证 · 纸质照片",
    country: "加拿大",
    mode: "纸质递交",
    widthPx: 827,
    heightPx: 1063,
    widthMm: 35,
    heightMm: 45,
    headRatio: [31 / 45, 36 / 45],
    note: "至少 35 × 45 mm；下巴至头顶 31–36 mm。像素按 600 DPI 导出，仅供打印排版参考。",
    verifiedAt: "2026-07-21",
    source: "https://www.canada.ca/en/immigration-refugees-citizenship/services/application/application-forms-guides/temporary-resident-visa-application-photograph-specifications.html",
  },
  {
    id: "gb-visa-digital",
    name: "签证申请 · 数字照片",
    country: "英国",
    mode: "在线申请",
    widthPx: 600,
    heightPx: 750,
    minBytes: 50 * 1024,
    maxBytes: 6 * 1024 * 1024,
    note: "至少 600 × 750 px，JPEG，50 KB–6 MB，竖向照片。",
    verifiedAt: "2026-07-21",
    source: "https://www.gov.uk/guidance/how-to-take-a-photo-for-a-visa-application-or-permission",
  },
  {
    id: "schengen-short-stay-print",
    name: "短期签证 · 纸质照片",
    country: "申根",
    mode: "纸质递交",
    widthPx: 827,
    heightPx: 1063,
    widthMm: 35,
    heightMm: 45,
    headRatio: [0.7, 0.8],
    note: "35 × 45 mm；近期彩色正面照，浅色背景，脸部约占照片高度 70%–80%。递交前请核对受理国要求。",
    verifiedAt: "2026-07-21",
    source: "https://home-affairs.ec.europa.eu/document/download/71052552-a6e7-4581-9857-04fb5ace6bc5_en",
  },
  {
    id: "jp-entry-visa-print",
    name: "入境签证 · 纸质照片",
    country: "日本",
    mode: "申请表粘贴",
    widthPx: 827,
    heightPx: 1063,
    widthMm: 35,
    heightMm: 45,
    note: "约 45 × 35 mm；正面、脱帽、无背景，通常要求近 6 个月拍摄。请核对所属领区使用的申请表版本。",
    verifiedAt: "2026-07-21",
    source: "https://www.mofa.go.jp/j_info/visit/visa/pdfs/application1_k.pdf",
  },
  {
    id: "kr-entry-visa-print",
    name: "入境签证 · 纸质照片",
    country: "韩国",
    mode: "申请表粘贴",
    widthPx: 827,
    heightPx: 1063,
    widthMm: 35,
    heightMm: 45,
    note: "35 × 45 mm；近 6 个月拍摄、正面免冠、白色或近白背景的彩色照片。",
    verifiedAt: "2026-07-21",
    source: "https://overseas.mofa.go.kr/upload/cntnts/cn-guangzhou-zh/visa_gw.pdf",
  },
  {
    id: "nz-visa-online",
    name: "签证申请 · 数字照片",
    country: "新西兰",
    mode: "在线申请",
    widthPx: 900,
    heightPx: 1200,
    minBytes: 512 * 1024,
    maxBytes: Math.round(3.14 * 1024 * 1024),
    headRatio: [0.7, 0.8],
    allowBackgroundRemoval: false,
    note: "3:4 JPG/JPEG，512 KB–3.14 MB；脸部占画面 70%–80%。官方禁止 AI 或数字换背景，本模板会保留原始背景。",
    verifiedAt: "2026-07-22",
    source: "https://www.immigration.govt.nz/process-to-apply/applying-for-a-visa/applying-online/uploading-documents-and-photos/visa-and-nzeta-photos/",
  },
  {
    id: "sg-entry-visa-online",
    name: "入境签证 · 数字照片",
    country: "新加坡",
    mode: "SAVE 在线申请",
    widthPx: 400,
    heightPx: 514,
    maxBytes: 60 * 1024,
    note: "JPEG，400 × 514 px，小于 60 KB；近期彩色正面照，白色背景。",
    verifiedAt: "2026-07-22",
    source: "https://www.ica.gov.sg/docs/default-source/ica/files/save-non-pub-ava_sp-user-guide-for-family-visa-application.pdf",
  },
  {
    id: "in-evisa-digital",
    name: "e-Visa · 数字照片",
    country: "印度",
    mode: "在线申请",
    widthPx: 600,
    heightPx: 600,
    minBytes: 10 * 1024,
    maxBytes: 1024 * 1024,
    note: "JPEG 正方形，10 KB–1 MB；官方上传范围为 350–1000 px，本模板输出 600 × 600 px。白色或浅色背景，不戴眼镜。",
    verifiedAt: "2026-07-22",
    source: "https://indianvisaonline.gov.in/visa/tvoa.html",
  },
];

export const unsupportedSpecs = [
  { country: "澳大利亚", detail: "ImmiAccount 内上传 JPG 并框选；官方未给出统一强制像素" },
];
